version: "3"
services:

  api:
    image: logger:latest
    build:
      context: .
    container_name: api
    env_file:
      - .env
    depends_on:
      - db
    ports:
    - "8080:8080"

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

